# Generated by Django 3.1.7 on 2021-04-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botusers',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
