# Generated by Django 3.1.7 on 2021-04-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0002_auto_20210409_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='botusers',
            name='lang',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
