# Generated by Django 3.1.7 on 2021-04-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0003_botusers_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='botusers',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
