# Generated by Django 3.1.7 on 2021-04-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0005_file_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
