# Generated by Django 3.1.7 on 2021-04-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0006_file_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbek"), ('FR', 'Русский')], default='uz', max_length=10),
        ),
    ]
