# Generated by Django 3.1.7 on 2021-04-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0007_subject_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='language',
        ),
        migrations.AddField(
            model_name='file',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbek"), ('FR', 'Русский')], default='uz', max_length=10),
        ),
    ]
