# Generated by Django 3.1.7 on 2021-04-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0009_auto_20210413_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.AddField(
            model_name='subject',
            name='name_uz',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
