# Generated by Django 3.1.7 on 2021-04-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0010_auto_20210413_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='botusers',
            name='last_test_no',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_ru',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_uz',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
