# Generated by Django 3.2 on 2021-04-29 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0011_auto_20210417_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='subject_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tgapp.subject'),
        ),
    ]
